language: go
go: 1.8.3
dist: trusty
group: edge

services:
- rabbitmq
- docker
- redis

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'
  - REDIS_URL="redis://"

addons:
  artifacts:
    paths:
    - ./build/linux/amd64/travis-worker
    - ./build/darwin/amd64/travis-worker
    target_paths:
    - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    - travis-ci/worker/$(git describe --always --dirty --tags)
    - travis-ci/worker/$TRAVIS_BRANCH

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
- go get github.com/FiloSottile/gvt
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
- curl -o ~/bin/shfmt -sSL https://github.com/mvdan/sh/releases/download/v2.0.0/shfmt_v2.0.0_linux_amd64
- chmod +x ~/bin/shfmt
- shfmt -version
- gem install package_cloud --no-ri --no-rdoc

script:
- travis_retry make deps
- make lintall
- make test
- make crossbuild
- make smoke

after_success:
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - sed -i s/@@BRANCH/$TRAVIS_BRANCH/ script/send-docker-hub-trigger
  - script/send-docker-hub-trigger

notifications:
  slack:
    secure: IyWrJhruYYHEIvi4YsN3vV2rycctnRiIolzUMwgiDo275AK6O4h58+fu1EXFjMZmCqdOan98MsF709yW3S9zDaZo2s233dKWzQ95S8+n2RS+pGsxBZacCiEvOh0u1K3f19hpf8zj0ybtpcox+a6yrxK+F3er9WveO39yPZjzwCA=
