language: go

go: 1.13.x

dist: xenial

cache:
  directories:
  - vendor
  - $HOME/.cache/go-build
  - $HOME/gopath/bin
  - $HOME/gopath/pkg/mod

services:
- rabbitmq
- docker
- redis

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'
  - REDIS_URL="redis://"

stages:
- test

before_cache:
- make clean

jobs:
  include:
  - stage: test
    name: linux
    go: 1.13.x
    script:
    - make deps
    - make lintall
    - GO111MODULE=on make build
    - mkdir -p build/linux/amd64
    - cp ${GOPATH%%:*}/bin/travis-worker build/linux/amd64
    - make test-no-cover
    - make test-cover
    - make smoke
    addons:
      apt:
        packages:
        - rabbitmq-server
      artifacts:
        paths:
        - ./build/linux/amd64/travis-worker
        target_paths:
        - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
        - travis-ci/worker/$(git describe --always --dirty --tags)
        - travis-ci/worker/$TRAVIS_BRANCH
  - stage: test
    name: crossbuild
    go: 1.13.x
    script:
    - GO111MODULE=on make build/darwin/amd64/travis-worker
    addons:
      artifacts:
        paths:
        - ./build/darwin/amd64/travis-worker
        target_paths:
        - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
        - travis-ci/worker/$(git describe --always --dirty --tags)
        - travis-ci/worker/$TRAVIS_BRANCH
  - stage: test
    name: docker
    if: type != 'pull_request' && env(DOCKER_LOGIN_PASSWORD) is present && env(DOCKER_LOGIN_USERNAME) is present
    script:
    - make docker-build
    - make smoke-docker
    - make docker-push
    - make send-docker-hub-trigger
    addons:
      apt:
        update: true
        packages:
        - docker-ce
  - stage: test
    name: http-job-test
    script:
    - GO111MODULE=on make build
    - mkdir -p build/linux/amd64
    - cp ${GOPATH%%:*}/bin/travis-worker build/linux/amd64
    - make http-job-test
