language: go
go: 1.8.3
dist: trusty
group: edge

services:
- rabbitmq
- docker
- redis

env:
  global:
  - AMQP_URI="amqp://"
  - GOPATH="$HOME/gopath"
  - PATH="bin:$HOME/gopath/bin:$HOME/bin:$PATH"
  - CHECKOUT_ROOT="$HOME/gopath/src/github.com/travis-ci/worker"
  - GO15VENDOREXPERIMENT='1'
  - REDIS_URL="redis://"

addons:
  artifacts:
    paths:
    - ./build/linux/amd64/travis-worker
    - ./build/darwin/amd64/travis-worker
    target_paths:
    - travis-ci/worker/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
    - travis-ci/worker/$(git describe --always --dirty --tags)
    - travis-ci/worker/$TRAVIS_BRANCH

install:
- go get github.com/FiloSottile/gvt
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install
- git clone --branch v1.3.1 https://github.com/mvdan/sh.git "${GOPATH%%:*}/src/github.com/mvdan/sh"
- go get github.com/mvdan/sh/...
- shfmt -version
- gem install package_cloud --no-ri --no-rdoc

script:
- travis_retry make deps
- make lintall
- make test
- make crossbuild
- make smoke
- if [[ $TRAVIS_PULL_REQUEST = 'false' && $PACKAGECLOUD_TOKEN ]]; then
    make package smoke-package;
  fi

jobs:
  include:
  - stage: 'Testing time'
  - stage: ':ship: to Docker Hub'
    install: skip
    script: if [[ $TRAVIS_PULL_REQUEST = 'false' && $DOCKER_LOGIN_PASSWORD && $DOCKER_LOGIN_USERNAME ]]; then
        make docker-build smoke-docker docker-push;
      fi

notifications:
  slack:
    secure: IyWrJhruYYHEIvi4YsN3vV2rycctnRiIolzUMwgiDo275AK6O4h58+fu1EXFjMZmCqdOan98MsF709yW3S9zDaZo2s233dKWzQ95S8+n2RS+pGsxBZacCiEvOh0u1K3f19hpf8zj0ybtpcox+a6yrxK+F3er9WveO39yPZjzwCA=
